

--INSERT INTO State VALUES (1,'Abia',1,0);
--INSERT INTO State VALUES (1,'Akwa-Ibom',1,0);
--INSERT INTO State VALUES (1,'Anambra',1,0);
--INSERT INTO State VALUES (1,'Bauchi',1,0);
--INSERT INTO State VALUES (1,'Bayelsa',1,0);
--INSERT INTO State VALUES (1,'Benue',1,0);
--INSERT INTO State VALUES (1,'Borno',1,0);
--INSERT INTO State VALUES (1,'Cross River',1,0);
--INSERT INTO State VALUES (1,'Delta',1,0);
--INSERT INTO State VALUES (1,'Ebonyi',1,0);
--INSERT INTO State VALUES (1,'Edo',1,0);
--INSERT INTO State VALUES (1,'Ekiti',1,0);
--INSERT INTO State VALUES (1,'Enugu',1,0);
--INSERT INTO State VALUES (1,'Gombe',1,0);
--INSERT INTO State VALUES (1,'Imo',1,0);
--INSERT INTO State VALUES (1,'Jigawa',1,0);
--INSERT INTO State VALUES (1,'Kaduna',1,0);
--INSERT INTO State VALUES (1,'Kano',1,0);
--INSERT INTO State VALUES (1,'Katsina',1,0);
--INSERT INTO State VALUES (1,'Kebbi',1,0);
--INSERT INTO State VALUES (1,'Kogi',1,0);
--INSERT INTO State VALUES (1,'Kwara',1,0);
--INSERT INTO State VALUES (1,'Lagos',1,0);
--INSERT INTO State VALUES (1,'Nasarawa',1,0);
--INSERT INTO State VALUES (1,'Niger',1,0);
--INSERT INTO State VALUES (1,'Ogun',1,0);
--INSERT INTO State VALUES (1,'Ondo',1,0);
--INSERT INTO State VALUES (1,'Osun',1,0);
--INSERT INTO State VALUES (1,'Oyo',1,0);
--INSERT INTO State VALUES (1,'Plateau',1,0);
--INSERT INTO State VALUES (1,'Rivers',1,0);
--INSERT INTO State VALUES (1,'Sokoto',1,0);
--INSERT INTO State VALUES (1,'Taraba',1,0);
--INSERT INTO State VALUES (1,'Yobe',1,0);
--INSERT INTO State VALUES (1,'Zamfara',1,0);
--INSERT INTO State VALUES (1,'Abuja',1,0);

INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (1, 'Abia', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (2, 'Akwa-Ibom', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (3, 'Anambra', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (4, 'Bauchi', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (5, 'Bayelsa', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (6, 'Benue', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (7, 'Borno', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (8, 'Cross River', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (9, 'Delta', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (10, 'Ebonyi', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (11, 'Edo', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (12, 'Ekiti', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (13, 'Enugu', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (14, 'Gombe', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (15, 'Imo', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (16, 'Jigawa', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (17, 'Kaduna', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (18, 'Kano', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (19, 'Katsina', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (20, 'Kebbi', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (21, 'Kogi', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (22, 'Kwara', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (23, 'Lagos', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (24, 'Nasarawa', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (25, 'Niger', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (26, 'Ogun', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (27, 'Ondo', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (28, 'Osun', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (29, 'Oyo', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (30, 'Plateau', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (31, 'Rivers', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (32, 'Sokoto', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (33, 'Taraba', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (34, 'Yobe', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (35, 'Zamfara', '1', 0, 1);
INSERT INTO States (Id, Name, DeliveryFee, Deleted, Active) VALUES (36, 'Abuja', '1', 0, 1);
